version: '3'
services:
  mysql_acl_lara:
    build: ./mysql
    container_name: acl_lara_mysql
    ports:
      - '5011:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      lara:
        ipv4_address: 192.168.101.4
  app_laravel:
    tty: true
    build: ./app_laravel
    container_name: acl_laravel
    volumes:
      - ./acl-management-system:/var/www/html:cached
    ports:
      - '5012:80'
    networks:
      lara:
        ipv4_address: 192.168.101.7
    depends_on:
      - mysql_acl_lara
  lara_servphp7:
    tty: true
    build: ./lara_servphp7
    container_name: lara_acl_php7
    volumes:
      - /Users/hashimoto/git/soe_serv:/var/www/html
      - /Users/hashimoto/git:/var/git
    ports:
      - '5015:80'
    networks:
      lara:
        ipv4_address: 192.168.101.6
    depends_on:
      - mysql_acl_lara

networks:
  lara:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.101.0/24
#        gateway: 192.168.100.1

